backend:
  name: github
  repo: sorrowglowworm/swimshark-site
  branch: main
  base_url: https://swimsk.com
  auth_endpoint: api/auth

publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://swimsk.com
logo_url: https://swimsk.com/assets/logo.png   # 可选
